CREATE SCHEMA IF NOT EXISTS ot_shoujijiaoyi;

CREATE TABLE IF NOT EXISTS ot_shoujijiaoyi.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (role, username)
);

CREATE TABLE IF NOT EXISTS ot_shoujijiaoyi.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  status TEXT,
  owner TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT,
  extra JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO ot_shoujijiaoyi.accounts (id, role, username, password, display_name) VALUES
  (1, 'admin', 'admin', '123456', '平台管理员'),
  (2, 'user', '17759573851', '123456', '商城用户'),
  (3, 'staff', 'newbee-admin1', '123456', '运营账号')
ON CONFLICT (role, username) DO UPDATE SET
  password = EXCLUDED.password,
  display_name = EXCLUDED.display_name;

INSERT INTO ot_shoujijiaoyi.items (id, module_key, title, subtitle, status, owner, amount, description, extra) VALUES
  (1, 'product', '手机商品演示记录1', '商品标题、分类、价格、库存和上架状态', '进行中', '平台管理员', 10, '手机交易商城的手机商品模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (2, 'product', '手机商品演示记录2', '商品标题、分类、价格、库存和上架状态', '待处理', '商城用户', 20, '手机交易商城的手机商品模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (3, 'product', '手机商品演示记录3', '商品标题、分类、价格、库存和上架状态', '已完成', '运营账号', 30, '手机交易商城的手机商品模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (4, 'category', '分类管理演示记录1', '手机品牌、系列、层级和排序', '进行中', '平台管理员', 10, '手机交易商城的分类管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (5, 'category', '分类管理演示记录2', '手机品牌、系列、层级和排序', '待处理', '商城用户', 20, '手机交易商城的分类管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (6, 'category', '分类管理演示记录3', '手机品牌、系列、层级和排序', '已完成', '运营账号', 30, '手机交易商城的分类管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (7, 'carousel', '首页轮播演示记录1', '首页推荐图、跳转地址和排序', '进行中', '平台管理员', 10, '手机交易商城的首页轮播模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (8, 'carousel', '首页轮播演示记录2', '首页推荐图、跳转地址和排序', '待处理', '商城用户', 20, '手机交易商城的首页轮播模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (9, 'carousel', '首页轮播演示记录3', '首页推荐图、跳转地址和排序', '已完成', '运营账号', 30, '手机交易商城的首页轮播模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (10, 'cart', '购物车演示记录1', '加购、数量、价格和结算准备', '进行中', '平台管理员', 10, '手机交易商城的购物车模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (11, 'cart', '购物车演示记录2', '加购、数量、价格和结算准备', '待处理', '商城用户', 20, '手机交易商城的购物车模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (12, 'cart', '购物车演示记录3', '加购、数量、价格和结算准备', '已完成', '运营账号', 30, '手机交易商城的购物车模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (13, 'order', '订单管理演示记录1', '订单、明细、支付和配送状态', '进行中', '平台管理员', 10, '手机交易商城的订单管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (14, 'order', '订单管理演示记录2', '订单、明细、支付和配送状态', '待处理', '商城用户', 20, '手机交易商城的订单管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (15, 'order', '订单管理演示记录3', '订单、明细、支付和配送状态', '已完成', '运营账号', 30, '手机交易商城的订单管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (16, 'user', '用户管理演示记录1', '用户、地址、联系方式和禁用状态', '进行中', '平台管理员', 10, '手机交易商城的用户管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (17, 'user', '用户管理演示记录2', '用户、地址、联系方式和禁用状态', '待处理', '商城用户', 20, '手机交易商城的用户管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (18, 'user', '用户管理演示记录3', '用户、地址、联系方式和禁用状态', '已完成', '运营账号', 30, '手机交易商城的用户管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  module_key = EXCLUDED.module_key,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  status = EXCLUDED.status,
  owner = EXCLUDED.owner,
  amount = EXCLUDED.amount,
  description = EXCLUDED.description,
  extra = EXCLUDED.extra,
  updated_at = now();

SELECT setval(pg_get_serial_sequence('ot_shoujijiaoyi.accounts', 'id'), COALESCE((SELECT MAX(id) FROM ot_shoujijiaoyi.accounts), 1), true);
SELECT setval(pg_get_serial_sequence('ot_shoujijiaoyi.items', 'id'), COALESCE((SELECT MAX(id) FROM ot_shoujijiaoyi.items), 1), true);

CREATE OR REPLACE FUNCTION public.ot_shoujijiaoyi_demo_rest(
  p_table_name TEXT,
  p_method TEXT DEFAULT 'GET',
  p_query JSONB DEFAULT '{}'::jsonb,
  p_payload JSONB DEFAULT '{}'::jsonb
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_schema CONSTANT TEXT := 'ot_shoujijiaoyi';
  v_table TEXT;
  v_sql TEXT;
  v_rows JSONB := '[]'::jsonb;
  v_key TEXT;
  v_value TEXT;
  v_where TEXT := '';
  v_order TEXT := '';
  v_limit TEXT := '';
  v_set TEXT := '';
  v_columns TEXT := '';
  v_values TEXT := '';
BEGIN
  IF p_table_name NOT IN ('accounts', 'items') THEN
    RAISE EXCEPTION 'table is not allowed: %', p_table_name;
  END IF;

  v_table := format('%I.%I', v_schema, p_table_name);

  FOR v_key, v_value IN SELECT key, value #>> '{}' FROM jsonb_each(p_query)
  LOOP
    IF v_key = 'select' THEN
      CONTINUE;
    ELSIF v_key = 'order' THEN
      v_order := ' ORDER BY ' || quote_ident(split_part(v_value, '.', 1)) ||
        CASE WHEN lower(split_part(v_value, '.', 2)) = 'desc' THEN ' DESC' ELSE ' ASC' END;
    ELSIF v_key = 'limit' THEN
      v_limit := ' LIMIT ' || LEAST(GREATEST(v_value::int, 1), 200);
    ELSIF v_value LIKE 'eq.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' = ' || quote_literal(substring(v_value FROM 4));
    ELSIF v_value LIKE 'ilike.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' ILIKE ' || quote_literal(substring(v_value FROM 7));
    END IF;
  END LOOP;

  IF upper(p_method) = 'GET' THEN
    v_sql := 'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (SELECT * FROM ' || v_table || v_where || v_order || v_limit || ') t';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'POST' THEN
    SELECT string_agg(quote_ident(key), ', '), string_agg(quote_literal(value #>> '{}'), ', ')
      INTO v_columns, v_values
    FROM jsonb_each(p_payload)
    WHERE key <> 'id';
    IF v_columns IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'INSERT INTO ' || v_table || ' (' || v_columns || ') VALUES (' || v_values || ') RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'PATCH' THEN
    SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value #>> '{}'), ', ')
      INTO v_set
    FROM jsonb_each(p_payload)
    WHERE key <> 'id' AND key <> 'created_at';
    IF v_set IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'UPDATE ' || v_table || ' SET ' || v_set || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'DELETE' THEN
    v_sql := 'DELETE FROM ' || v_table || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  END IF;

  RAISE EXCEPTION 'method is not allowed: %', p_method;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ot_shoujijiaoyi_demo_rest(TEXT, TEXT, JSONB, JSONB) TO anon, authenticated, service_role;
